name: docker build cryptobot:next_release
on:
  push:
    branches:
      - "next_release"

jobs:
  push_to_registry:
    name: Push Docker image to GitHub Container Registry
    runs-on: self-hosted
    permissions:
      packages: write
      contents: write
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
        with:
          fetch-depth