name: Tag new release
on:
  push:
    branches: master
jobs:
  tag_and_release:
    name: Create and push new tag and release
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: write
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Bump version and push tag
        id: tag_version
        uses: mathieudutour/github-tag-action@v5.6
        with:
          github_token: ${{ secrets.PAT_REPO }}

      - name: Creat